import type { CapacitorConfig } from '@capacitor/cli';

/**
 * Android wrapper configuration.
 *
 * The React build (dist/) is packaged into an Android WebView app.
 * The `android/` native project is generated by `npm run android:init`
 * and committed to the repo — you only run that command once.
 *
 * Per-release flow:
 *   npm run build            # fresh web bundle
 *   npx cap sync android     # copy bundle into android/app
 *   npm run android:apk      # assemble release APK
 */
const config: CapacitorConfig = {
  appId: 'com.sakshamfit.schoolmanagement',
  appName: 'School Management',
  webDir: 'dist',
  android: {
    allowMixedContent: false,
  },
};

export default config;
